spring.application.name=maroom

spring.datasource.url=jdbc:postgresql://db.yoamljhncyfakzunznls.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Maroom_DB_2026!Supabase

spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true