spring.application.name=maroom

spring.datasource.url=jdbc:postgresql://localhost:5432/maroom
spring.datasource.username=inhahwang
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true