export const icons = {
  rooms: require("./rooms.png"),
  explore: require("./explore.png"),
  home: require("./home.png"),
  heart_bottom: require("./heart_bottom.png"),
  profile: require("./profile.png"),
  X: require("./X.png"),
  heart: require("./heart.png"),
  backButton: require("./backButton.png"),
  MAROOM_LOGO: require("./MAROOM_LOGO.png"),
  X_White: require("./X_white.png"),
  search: require("./search.png"),
  filter: require("./filter.png"),
  google: require("./google.png"),
  onboarding_image: require("./onboarding_image.png"),
  maroon_onboarding: require("./maroon_onboarding.png"),
  LOGO2: require("./MAROOM_LOGO2.png"),
  new_spinner: require("./new_spinner.png"),
  appLogo: require("../app-logo.png"),
};
