spring.application.name=maroom
spring.config.import=optional:file:.env.local[.properties]

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.yoamljhncyfakzunznls
spring.datasource.password=Maroom_DB_2026!Supabase

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.data-source-properties.preferQueryMode=simple

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
